<c:set var="bodyback_c" value="#FFFFFF"/>
<c:set var="back_c" value="#8fbc8f"/>
<c:set var="title_c" value="#5f9ea0"/>
<c:set var="value_c" value="#b0e0e6"/>
<c:set var="bar" value="#778899"/>
<c:set var="tt" value="#FF6CFF"/>
<c:set var="bb" value="#000000"/>
<c:set var="ww" value="#FFFFFF"/>
<c:set var="gg" value="#EAEAEA"/>
<c:set var="sky" value=""/>